# Generated by Django 4.0.6 on 2022-09-01 18:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htp_app', '0002_alter_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='poster',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
